-- ----------------------------
-- Table structure for "C##FHBOOT"."DICTDATA"
-- ----------------------------
-- DROP TABLE "C##FHBOOT"."DICTDATA";
CREATE TABLE "C##FHBOOT"."DICTDATA" (
	"DICT_CODE" VARCHAR2(64 BYTE) NULL ,
	"PARENT_CODE" VARCHAR2(64 BYTE) NULL ,
	"PARENT_CODES" VARCHAR2(1000 BYTE) NULL ,
	"DICT_LABEL" VARCHAR2(100 BYTE) NULL ,
	"DICT_VALUE" VARCHAR2(100 BYTE) NULL ,
	"DICT_TYPE" VARCHAR2(100 BYTE) NULL ,
	"DESCRIPTION" VARCHAR2(500 BYTE) NULL ,
	"STATUS" VARCHAR2(1 BYTE) NULL ,
	"CREATE_BY" VARCHAR2(64 BYTE) NULL ,
	"CREATE_DATE" VARCHAR2(0 BYTE) NULL ,
	"UPDATE_BY" VARCHAR2(64 BYTE) NULL ,
	"UPDATE_DATE" VARCHAR2(0 BYTE) NULL ,
	"REMARKS" VARCHAR2(500 BYTE) NULL ,
	"DICTDATA_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."DICT_CODE" IS '字典编码';
COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."PARENT_CODE" IS '父级编号';
COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."PARENT_CODES" IS '所有父级编号';
COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."DICT_LABEL" IS '字典标签';
COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."DICT_VALUE" IS '字典键值';
COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."DICT_TYPE" IS '字典类型';
COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."DESCRIPTION" IS '字典描述';
COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."STATUS" IS '状态（0正常 1删除 2停用）';
COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."UPDATE_DATE" IS '更新时间';
COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."REMARKS" IS '备注信息';
COMMENT ON COLUMN "C##FHBOOT"."DICTDATA"."DICTDATA_ID" IS 'ID';

-- ----------------------------
-- Indexes structure for table DICTDATA
-- ----------------------------

-- ----------------------------
-- Checks structure for table "C##FHBOOT"."DICTDATA"

-- ----------------------------

ALTER TABLE "C##FHBOOT"."DICTDATA" ADD CHECK ("DICTDATA_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "C##FHBOOT"."DICTDATA"
-- ----------------------------
ALTER TABLE "C##FHBOOT"."DICTDATA" ADD PRIMARY KEY ("DICTDATA_ID");
