GO
/****** FHQfsci ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE DICTDATA (
 		DICTDATA_ID  nvarchar(100) NOT NULL,
		DICT_CODE nvarchar(64) DEFAULT NULL,
		PARENT_CODE nvarchar(64) DEFAULT NULL,
		PARENT_CODES nvarchar(1000) DEFAULT NULL,
		DICT_LABEL nvarchar(100) DEFAULT NULL,
		DICT_VALUE nvarchar(100) DEFAULT NULL,
		DICT_TYPE nvarchar(100) DEFAULT NULL,
		DESCRIPTION nvarchar(500) DEFAULT NULL,
		STATUS nvarchar(1) DEFAULT NULL,
		CREATE_BY nvarchar(64) DEFAULT NULL,
		CREATE_DATE nvarchar(0) DEFAULT NULL,
		UPDATE_BY nvarchar(64) DEFAULT NULL,
		UPDATE_DATE nvarchar(0) DEFAULT NULL,
		REMARKS nvarchar(500) DEFAULT NULL,
PRIMARY KEY CLUSTERED 
(
	[DICTDATA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
